### ISSUE TITLE
harness-application template error 

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/cloud-harness#265] opened 2021-04-01 14:51 UTC
Steps to reproduce:

1. clone cloud-harness
2. install python requirements
3. add a new application to ch with harness-application strapi
3. Changed strapi > values.yaml > secured to true
4. start minikube
5. create strapi namespace
6. eval $(minikube docker-env)
7. (confirm kubectl context)
8. Ran harness-deployment . -i strapi -n strapi -b -l -dtls --deploy

Expected:
All pods working
 
Result:
Container image "strapi:latest" is not present with pull policy of Never
Error: ErrImageNeverPull

Workaround:
Move dockerfile from strapi > backend to strapi

**Comment by filippomc** [comment] 2021-04-01 17:11
This also makes me think that we may want to have a simple application template for applications based on a simple docker image extension

**Comment by filippomc** [comment] 2022-01-21 16:23
closing as duplicate of #216

**Closed by filippomc** 2022-01-21 16:23 UTC
Labels: bug, duplicate, scope:code-generation
